services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /app/src
        - path: ./backend/pom.xml
          action: rebuild
        - path: ./backend/.mvn
          action: rebuild
        - path: ./backend/mvnw
          action: rebuild

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /app/src
          ignore:
            - node_modules/
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/vite.config.js
          action: rebuild
    depends_on:
      - backend
